[versions]
agp = "9.3.2"
kotlin = "2.4.10"
libxposed = "102.0.0"
dexkit = "2.2.0"
activityCompose = "1.13.0"
composeMaterialIconsExtended = "1.7.8"
kotlinxCoroutines = "1.11.0"
miuix = "0.9.3"

[libraries]
libxposed-api = { module = "io.github.libxposed:api", version.ref = "libxposed" }
libxposed-service = { module = "io.github.libxposed:service", version.ref = "libxposed" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "composeMaterialIconsExtended" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
miuix-blur-android = { module = "top.yukonga.miuix.kmp:miuix-blur-android", version.ref = "miuix" }
miuix-icons-android = { module = "top.yukonga.miuix.kmp:miuix-icons-android", version.ref = "miuix" }
miuix-preference-android = { module = "top.yukonga.miuix.kmp:miuix-preference-android", version.ref = "miuix" }
miuix-ui-android = { module = "top.yukonga.miuix.kmp:miuix-ui-android", version.ref = "miuix" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
